apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apni-dukkan
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/suyash172003/Apni-Dukkan.git
    path: K8/manifests
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
