spring.application.name=Dukkan

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/dukkan?createDatabaseIfNotExists=true}
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:Saurabh@645}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=apnidukkan406@gmail.com
spring.mail.password=fpml vgmf dmnl gnjb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 

server.port=8081

paypal.mode=sandbox
paypal.client.Id=AWyMw7vrFZ_n6cE88OsUmFS0n6tgc0ELi8BcsqB7T_gmCcJHHld-aYfa0aX_1ls0_83k3RbhRKn7AJe1
paypal.client.secret=EI9SR2jJabdFprJ-eYnBMEegKRPG4_9hL0evmuFiJOMuQh272ni8ZIiVzYTe4lLmhRY3NNazXwgZulaY