apiVersion: apps/v1
kind: Deployment
metadata:
  name: apni-dukkan
  labels:
    app: apni-dukkan
  annotations:
    argocd-image-updater.argoproj.io/image-list: suyash172003/apni-dukkan
    argocd-image-updater.argoproj.io/my-container.update-strategy: latest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apni-dukkan
  template:
    metadata:
      labels:
        app: apni-dukkan
    spec:
      containers:
        - name: apni-dukkan
          image: suyash172003/apni-dukkan-app:676665latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_URL
              value: jdbc:mysql://mysql-service:3306/dukkan
            - name: MYSQL_USERNAME
              value: root
            - name: MYSQL_PASSWORD
              value: root
      restartPolicy: Always